# Generated by Django 5.2.3 on 2025-08-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('parent_email', models.EmailField(max_length=254)),
                ('grade', models.CharField(max_length=20)),
            ],
        ),
    ]
